improve

diff --git a/etc/darwin_installer b/etc/darwin_installer
--- a/etc/darwin_installer
+++ b/etc/darwin_installer
@@ -1,6 +1,12 @@
 #!/bin/sh
 set -eu
 
+trap catch ERR
+
+function catch() {
+  log_fail "Failed to installation."
+}
+
 # utility functions ------------------------------
 
 is_exists() {
@@ -110,6 +116,14 @@ log_echo() {
   logging TITLE "$1"
 }
 
+is_ci() {
+  if [[ "$CI" == "true" ]]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
 # install function ------------------------
 
 prepare() {
@@ -181,15 +195,25 @@ if [[ ! -d $dotpath ]]; then
 fi
 
 prepare
-setup_applications
+if ! is_ci; then
+  setup_applications
+fi
 setup_packages
 
+log_info "symbolic link: $dotpath/dotfiles/ to $HOME/dotfiles"
 ln -sf "$dotpath/dotfiles/" "$HOME/dotfiles"
+log_info "symbolic link: $dotpath/.zshenv to $HOME/.zshenv"
 ln -sf "$dotpath/.zshenv" "$HOME/.zshenv"
 log_pass "dotfiles OK."
 
 log_info "change shells..."
-if [[ -z $(cat /etc/shells | grep $SHELL) ]]; then
-  echo "$(brew --prefix)/bin/zsh" | sudo tee -a /etc/shells
+readonly shellpath="$(brew --prefix)/bin/zsh"
+if [[ -z $(cat /etc/shells | grep ${shellpath}) ]]; then
+  echo ${shellpath} | sudo tee -a /etc/shells
 fi
-echo -ne '\n' | sudo chsh -s "$(brew --prefix)/bin/zsh"
+echo -ne '\n' | sudo chsh -s ${shellpath}
+exec ${shellpath} -l
+echo "dotpath: $DOTPATH"
+echo "zdotdir: $ZDOTDIR"
+
+exit 0
