Update

diff --git a/etc/installer_darwin b/etc/installer_darwin
--- a/etc/installer_darwin
+++ b/etc/installer_darwin
@@ -128,6 +128,10 @@ is_ci() {
 
 prepare() {
   if is_not_exists brew; then
+    if is_not_exists ruby; then
+      log_fail "not found ruby..."
+      exit 1
+    fi
     ruby -e "$(curl -fsSL https://githubusercontent.com/Homebrew/install/master/install)"
     log_pass "Homebrew installation is completed."
   else
@@ -170,17 +174,11 @@ setup_applications() {
 
 # -----------------------------------------
 
-log_info "tool check..."
 
-declare -ax cmds=(git ruby)
-for c in ${cmds[@]};
-do
-  log_info "check: $c."
-  if is_not_exists $c; then
-    log_fail "not found $c."
-    exit 1
-  fi
-done
+if is_not_exists git; then
+  log_fail "not found git..."
+  exit 1
+fi
 
 log_info "start installing..."
 
